package org.example;

public enum State {
    IDLE,
    AWAITING_NAME,
    AWAITING_DATE,
    AWAITING_ID_TO_REMOVE,
    AWAITING_GIFT_OWNER_NUMBER,
    AWAITING_GIFT_NAME,
    AWAITING_GIFT_OWNER_NUMBER_TO_REMOVE,
    AWAITING_GIFT_NUMBER_TO_REMOVE,
    AWAITING_GIFT_OWNER_NUMBER_TO_VIEW,
    AWAITING_REMINDER_THEME,
    AWAITING_REMINDER_DAYS,
    AWAITING_REMINDER_TIME,
    AWAITING_REMINDER_NUMBER_TO_REMOVE;
}
